django_ajax_api/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from app_base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # Auth
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # Hall CRUD operations
    path('halloffame/create/', login_required(views.CreateHallView.as_view()), name='create_hall'),
    path('halloffame/', login_required(views.ListHallView.as_view()), name='list_hall'),
    path('halloffame/<int:pk>', login_required(views.DetailHallView.as_view()), name='detail_hall'),
    path('halloffame/<int:pk>/update', login_required(views.UpdateHallView.as_view()), name='update_hall'),
    path('halloffame/<int:pk>/delete', login_required(views.DeleteHallView.as_view()), name='delete_hall'),
    # Video
    path('halloffame/<int:pk>/addvideo', login_required(views.add_video), name='add_video'),
    path('video/search/', views.video_search, name='video_search'),
    path('ajax/add/video/', views.ajax_add_video, name='ajax_add_video'),
    path('halloffame/<int:pk>/deletevideo', login_required(views.DeleteVideo.as_view()), name='delete_video'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_base/models.py
from django.contrib.auth.models import User
from django.db import models


class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title}'


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.title}'

app_base/forms.py
from django import forms

from app_base.models import Video


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('url', )
        labels = {'url': 'Youtube URL'}


class VideoSearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for videos')

app_base/views.py
from urllib import parse


from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.forms.utils import ErrorList

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from app_base.forms import VideoForm, VideoSearchForm
from app_base.models import Hall, Video
import requests

YOUTUBE_API_KEY = 'AIzaSyAxQRR4U1uOPw_17Uc94YWcfF0eISHiKf4'


class MyLoginView(SuccessMessageMixin, LoginView):
    template_name = 'registration/login.html'
    success_message = 'Welcome to your profile'


def home(request):
    # # Flash message
    # messages.add_message(request, messages.SUCCESS, 'Hello world.')
    return render(request, 'app_base/home.html')


@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', context=dict(halls=halls))


@login_required
def add_video(request, pk):
    form = VideoForm()
    video_search_form = VideoSearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404
    if request.method == 'POST':
        form = VideoForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']

            video = Video()
            video.hall = hall
            video.url = url
            parsed_url = parse.urlparse(url)

            video_id = parse.parse_qs(parsed_url.query).get("v")
            print(video_id)
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(
                    f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet'
                    f'&id={video_id[0]}'
                    f'&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                print(title)
                video.title = title
                video.save()
                return redirect("detail_hall", pk)
            else:
                errors = form.errors.setdefault('url', ErrorList())
                errors.append('Need to be a youtube url')

    return render(request, 'halls/add_video.html',
                  dict(form=form, video_search_form=video_search_form, hall=hall))


def video_search(request):
    search_form = VideoSearchForm(request.GET)
    if search_form.is_valid():
        data = search_form.cleaned_data
        response = requests.get(f'https://youtube.googleapis.com/youtube/v3/'
                                f'search?part=snippet'
                                f'&maxResults=6'
                                f'&q={data["search_term"]}&key={YOUTUBE_API_KEY}')

        return JsonResponse(data=response.json())
    return JsonResponse(data={'error': 'Not able to validate form'})


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUpView, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


# CRUD

class ListHallView(generic.ListView):
    model = Hall
    template_name = 'halls/list.html'
    context_object_name = 'halls'

    def get_queryset(self, **kwargs):
        qs = super(ListHallView, self).get_queryset()
        return qs.filter(user=self.request.user)


class CreateHallView(generic.CreateView):
    model = Hall
    fields = ('title',)
    template_name = 'halls/create.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateHallView, self).form_valid(form)
        return redirect('dashboard')


class DetailHallView(generic.DetailView, PermissionRequiredMixin):
    model = Hall
    template_name = 'halls/detail_hall.html'


class UpdateHallView(generic.UpdateView):
    model = Hall
    template_name = 'halls/update_hall.html'
    fields = ('title',)
    success_url = reverse_lazy('dashboard')


class DeleteHallView(generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')


def ajax_add_video(request):
    if request.is_ajax() and request.method == 'POST':
        print("So far , so good")
        q_dict = request.POST.dict()
        print(q_dict)
        youtube_id = q_dict.get('id')
        pk = q_dict.get('pk')
        url = q_dict.get('url')
        title = q_dict.get('title')
        hall = Hall.objects.get(pk=pk)

        video = Video()
        video.hall = hall
        video.url = url
        video.youtube_id = youtube_id
        video.title = title

        video.save()
        return JsonResponse({})


class DeleteVideo(generic.DeleteView):
    model = Video
    template_name = 'video/delete_video.html'
    success_url = reverse_lazy('dashboard')

templates/_partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
            aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>

        </ul>
        <ul class="navbar-nav ml-auto" >
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" id="dropdownMenu"
                       aria-haspopup="true"
                       aria-expanded="false">{{ user.username }}</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu">
                        <a class="dropdown-item" href="#">Profile</a>
                        <a class="dropdown-item" href="{% url "dashboard" %}">Dashboard</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>

                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url 'signup' %}" role="button">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/app_base/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Hello, world!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention
            to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
        </p>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/flatly/bootstrap.min.css"
          integrity="sha384-qF/QmIAj5ZaYFAeQcrQ6bfVMAh4zZlrGwTPY7T/M+iTTLJqJBJjwwnsE5Y0mV7QK" crossorigin="anonymous">
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"#}
    {#          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">#}

    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
{% include '_partials/_navbar.html' %}
<div class="container my-5">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        setTimeout(function () {
            $('.alert').fadeOut(1600, "linear")
        }, 2000)
    </script>
    {% block content %}


    {% endblock %}
</div>


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"#}
{#        crossorigin="anonymous"></script>#}

<!-- Option 2: Separate Popper and Bootstrap JS -->


</body>
</html>

templates/dashbase.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome5-overrides.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/side_bar_wrapper.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/flatly/bootstrap.min.css"
          integrity="sha384-qF/QmIAj5ZaYFAeQcrQ6bfVMAh4zZlrGwTPY7T/M+iTTLJqJBJjwwnsE5Y0mV7QK" crossorigin="anonymous">
    {#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"#}
    {#          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">#}

    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>

<div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
        <div class="sidebar-heading">Start Bootstrap</div>
        <div class="list-group list-group-flush">
            <a href="#" class="list-group-item list-group-item-action bg-light">Dashboard</a>
            <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
            <a href="#" class="list-group-item list-group-item-action bg-light">Log out</a>
        </div>
    </div>

    <!-- Page Content -->
    <div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
            <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container-fluid">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                         role="alert" data-dismiss="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}

            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
{#<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"#}
{#        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"#}
{#        crossorigin="anonymous"></script>#}

<!-- Option 2: Separate Popper and Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'js/script.min.js' %}"></script>
<script>
    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>

</body>
</html>

templates/halls/add_video.html
{% extends 'base.html' %}

{% block title %}
    Add video
{% endblock %}

{% block content %}
    <h2>Add a video to {{ hall.title }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
            <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Add</button>
    </form>

    <h3 class="my-3">OR</h3>

    <form id="js-search-form" action="">
        {% load widget_tweaks %}
        {% for field in video_search_form %}
            <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}
        <button id="js-search_btn" type="button" class="btn btn-outline-primary">Search</button>
        <button id="js-clear_btn" type="button" class="btn btn-outline-success">Clear</button>

    </form>


    <div id="search_results" class="card-columns">

    </div>


    <script>
        $(document).ready(function () {
            $("#js-search_btn").on('click', function () {


                let $text = $("#id_search_term").val()
                if ($text === '') {
                    swal("You must search something !!");
                } else {

                    $.ajax({
                        url: "{% url 'video_search' %}",
                        data: {
                            search_term: $text
                        },
                        dataType: 'json',
                        success: function (data) {
                            let videos = data.items
                            let embedded_videos = videos.map(v =>
                                        `<div class="card my-4 h-100">
                                            <div class="card-body">
                                                <h5 class="card-title">${v['snippet']['title']}</h5>
                                                <iframe
                                                    width="100%" height="225"
                                                    src="https://www.youtube.com/embed/${v['id']['videoId']}?controls=0"
                                                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                                    allowfullscreen>
                                                </iframe>
                                            </div>
                                            <div class="card-footer">
                                                 <a href="#" class="btn btn-primary" onclick="add_video('${v['id']['videoId']}', '${v['snippet']['title']}')">Add video</a>
                                            </div>
                                        </div>`)
                            $('#search_results').append(embedded_videos)
                            $('#js-clear_btn').on("click", function () {
                                $('#search_results').empty()
                            })

                        }
                    })
                }
            })
        })

        {#let old_card =  `#}
        {#                <div class="col-md-4 mt-3">#}
        {#                    <div class="card mb-4 shadow-sm">#}
        {#                        <h5>${v['snippet']['title']}</h5>#}
        {#                        <iframe#}
        {#                            width="100%" height="225"#}
        {#                            src="https://www.youtube.com/embed/${v['id']['videoId']}?controls=0"#}
        {#                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"#}
        {#                            allowfullscreen>#}
        {#                        </iframe>#}
        {#                    </div>#}
        {#                    <a href="#" class="btn btn-primary" onclick="add_video('${v['id']['videoId']}', '${v['snippet']['title']}')">Add video</a>#}
        {#                </div>`#}

        card_example =
            `<div class="card">
                <img class="card-img-top" src="..." alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                    </div>
                <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div>
            </div>`

        function add_video(video_id, title) {
            let csrf_token = $("[name=csrfmiddlewaretoken]").val();
            $.ajax({
                url: "{% url 'ajax_add_video' %}",
                data: {
                    title: title,
                    id: video_id,
                    url: `https://www.youtube.com/watch?v=${video_id}`,
                    pk: {{ hall.pk }}
                },
                type: 'post',
                headers: {
                    "X-CSRFToken": csrf_token
                },
                dataType: 'json',
                success: function (data) {
                    swal({
                        title: "Done",
                        text: "Video added",
                        icon: "success",
                        button: "Ok!",
                    });
                }
            })
        }
    </script>


{% endblock %}

templates/halls/create.html
{% extends 'base.html' %}

{% block title %}
    Create a Hall
{% endblock %}

{% block content %}
    <h2>Create Hall of fame</h2>
       <form action="" method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
            <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
                {{ field.errors }}
            {{ field.label_tag }}
            {%  render_field field class="form-control" %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Create</button>
    </form>

{% endblock %}

templates/halls/dashboard.html
{% extends 'dashbase.html' %}
{% block title %}
    Dashboard
{% endblock %}


{% block content %}
    <h1>{{ user.username }}'s hall of fame</h1>
    <a href="{% url 'create_hall' %}" class="btn btn-outline-success">Create a new Hall of fame</a>
    <ul>
        {% for hall in halls %}
            <li class="list-unstyled my-4"><a href="{% url 'detail_hall' hall.pk %}">{{ hall.title }}</a></li>
            <div class="row">
                {% for video in hall.video_set.all %}
                    <div class="col-sm-6">
                        <div class="card my-3">
                            <div class="card-body">
                                <div class="embed-responsive embed-responsive-4by3 ">
                                    <iframe
                                            class="embed-responsive-item card-text"
                                            src="https://www.youtube.com/embed/{{ video.youtube_id }}?controls=0"
                                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                                            allowfullscreen>
                                    </iframe>

                                </div>
                                <a href="{% url 'delete_video' video.pk %}" class="btn btn-outline-danger my-2">Delete</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    </ul>


{% endblock %}

templates/halls/delete_hall.html
{% extends 'base.html' %}
{% block title %}
    Delete
{% endblock %}

{% block content %}
    <h3>Are you sure you want to delete this hall of fame?</h3>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
    <br>
    <h4><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h4>
{% endblock %}

templates/halls/detail_hall.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Detail
{% endblock %}

{% block content %}
    <h2>{{ hall.title }}</h2>

    <div class="list-group w-25">
        <a href="{% url 'add_video' hall.pk %}" class="list-group-item list-group-item-action list-group-item-success">Add a video</a>
        <a href="{% url 'update_hall' hall.pk %}" class="list-group-item list-group-item-action list-group-item-info">Edit Hall of fame</a>
        <a href="{% url 'delete_hall' hall.pk %}" class="list-group-item list-group-item-action list-group-item-danger">Delete Hall of fame</a>
    </div>
{% endblock %}

templates/halls/list.html
{% extends 'base.html' %}

{% block title %}
    List of Hall
{% endblock %}

{% block content %}
    {% for hall in halls %}
        <p>{{ hall.title }} &nbsp; <small><a href="{% url 'add_video' hall.pk %}">Add videos</a></small> </p>

    {% endfor %}
{% endblock %}

templates/halls/update_hall.html
{% extends 'base.html' %}

{% block title %}
    Update a Hall
{% endblock %}

{% block content %}
    <h2>Update Hall of fame</h2>
    <form action="" method="post">
        {% csrf_token %}
        {% load widget_tweaks %}
        {% for field in form %}
            <div class="form-group {% if field.errors %} alert alert-danger {% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-outline-primary">Save</button>
        <a href="{% url 'delete_hall' hall.pk %}" class="btn btn-outline-danger ">Delete</a>
    </form>

{% endblock %}

templates/video/delete_video.html
{% extends 'base.html' %}
{% block title %}
    Delete
{% endblock %}

{% block content %}
    <h3>Are you sure you want to delete this video?</h3>
    <div class="embed-responsive embed-responsive-4by3 w-50 my-3">
        <iframe
                class="embed-responsive-item card-text"
                src="https://www.youtube.com/embed/{{ video.youtube_id }}?controls=0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen>
        </iframe>

    </div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock %}